#ifndef ERRORLIST_H
#define ERRORLIST_H

#define LVM_SUCCESS 1
#define LVM_CODE_SEGEMENT_ERROR 0xf0
#define LVM_STACK_SEGEMENT_ERROR 0xf1
#define LVM_DATA_SEGEMENT_ERROR 0xf2
#define LVM_RIGISTER_SEGEMENT_ERROR 0xf3
#define LVM_BIN_OPEN_ERROR 0xf4
#define LVM_BIN_READ_ERROR 0xf5
#define LVM_EXECUTE_ERROR 0xf6
#endif // !ERRORLIST_H

